更新機能の追加
s1F102201649/django-test-exercise pull request #6
Opened 2023-07-19 04:16 UTC by s1f102202437

更新機能追加しました。確認よろしくお願いします！

2023-07-19 08:40 UTC, s1F102201649 requested changes
todo/views.pyのtask.save()が抜けているので追加をお願いします。

2023-07-19 08:40 UTC, s1F102201649 commented on todo/views.py
> +        return redirect(detail, task_id)
task.save()が抜けているので追加をお願いします

2023-07-20 04:05 UTC, s1f102202437 commented on todo/views.py
> +        return redirect(detail, task_id)
了解です！訂正しました。

2023-07-20 04:21 UTC, s1F102201649 approved these changes
確認しました。ありがとうございました。

2023-07-20 04:45 UTC, merged